"use client";

import { createContext, useContext, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarPlus, Clock3, X } from "lucide-react";
import { createAppointment, updateAppointmentStatus } from "@/app/actions/modules";
import { Button } from "@/components/ui/button";
import { defaultTemplateExamples, type TemplateExamples } from "@/lib/platform-config";

type Option = { id: string; name: string };
export type AppointmentRow = { id: string; title: string; customer: string; service: string; staff: string; startsAt: string; endsAt: string; date: string; time: string; status: "SCHEDULED" | "CONFIRMED" | "COMPLETED" | "CANCELLED" | "NO_SHOW"; notes: string };
const AppointmentExamplesContext = createContext(defaultTemplateExamples);

export function AppointmentManager({ appointments, customers, services, staff, examples = defaultTemplateExamples }: { appointments: AppointmentRow[]; customers: Option[]; services: Option[]; staff: Option[]; examples?: TemplateExamples }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function create(formData: FormData) { setSaving(true); const result = await createAppointment({ title: String(formData.get("title")), customerId: String(formData.get("customerId")), serviceId: String(formData.get("serviceId")), staffId: String(formData.get("staffId")), startsAt: String(formData.get("startsAt")), endsAt: String(formData.get("endsAt")), notes: String(formData.get("notes")) }); setSaving(false); if (!result.ok) { setError(result.error); return; } setOpen(false); setError(""); router.refresh(); }
  async function changeStatus(id: string, status: AppointmentRow["status"]) { const result = await updateAppointmentStatus({ id, status }); if (!result.ok) setError(result.error); else router.refresh(); }
  return <AppointmentExamplesContext.Provider value={examples}><>
    <div className="flex justify-end"><Button onClick={() => setOpen(true)}><CalendarPlus size={16} /> New appointment</Button></div>
    {error ? <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-xs font-semibold text-red-700">{error}</p> : null}
    <div className="mt-4 overflow-hidden rounded-xl border border-[var(--border)] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-[var(--border)] bg-slate-50 text-[10px] uppercase tracking-wider text-slate-500"><th className="px-5 py-3">Date & time</th><th className="px-4 py-3">Appointment</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Staff</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{appointments.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="text-xs font-bold text-slate-800">{item.date}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 size={11} /> {item.time}</p></td><td className="px-4 py-4"><p className="text-xs font-bold text-slate-800">{item.title}</p><p className="mt-1 text-[10px] text-slate-400">{item.service}</p>{item.notes ? <p className="mt-1 max-w-xs truncate text-[10px] text-slate-400">{item.notes}</p> : null}</td><td className="px-4 py-4 text-xs text-slate-600">{item.customer}</td><td className="px-4 py-4 text-xs text-slate-600">{item.staff}</td><td className="px-5 py-4"><select value={item.status} onChange={(event) => changeStatus(item.id, event.target.value as AppointmentRow["status"])} className="h-9 rounded-lg border border-[var(--border)] bg-white px-2 text-xs font-semibold"><option value="SCHEDULED">Scheduled</option><option value="CONFIRMED">Confirmed</option><option value="COMPLETED">Completed</option><option value="NO_SHOW">No-show</option><option value="CANCELLED">Cancelled</option></select></td></tr>)}</tbody></table></div>{!appointments.length ? <div className="px-6 py-14 text-center"><CalendarPlus className="mx-auto text-slate-300" size={28} /><p className="mt-3 text-sm font-bold text-slate-700">No appointments yet</p><p className="mt-1 text-xs text-slate-500">Schedule the first customer visit.</p></div> : null}<div className="border-t border-[var(--border)] px-5 py-3 text-[11px] text-slate-500">{appointments.length} appointment{appointments.length === 1 ? "" : "s"}</div></div>
    {open ? <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/50 p-4"><form action={create} className="my-8 w-full max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--border)] px-6 py-5"><div><h2 className="text-lg font-bold">New appointment</h2><p className="mt-1 text-xs text-slate-500">Schedule a service or customer visit.</p></div><button type="button" onClick={() => setOpen(false)}><X size={19} className="text-slate-400" /></button></div><div className="grid gap-4 p-6 sm:grid-cols-2"><Field name="title" label="Title" placeholder="Service appointment" className="sm:col-span-2" /><Select name="customerId" label="Customer" options={customers} empty="Walk-in / no customer" /><Select name="serviceId" label="Service" options={services} empty="No linked service" /><Select name="staffId" label="Assigned staff" options={staff} empty="Unassigned" /><span /><Field name="startsAt" type="datetime-local" label="Start" /><Field name="endsAt" type="datetime-local" label="End" /><label className="sm:col-span-2"><span className="mb-2 block text-xs font-bold text-slate-700">Notes</span><textarea name="notes" rows={3} className="w-full rounded-lg border border-[var(--border)] p-3 text-sm outline-none" /></label>{error ? <p className="sm:col-span-2 text-xs font-semibold text-red-700">{error}</p> : null}</div><div className="flex justify-end gap-2 border-t border-[var(--border)] p-4"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Scheduling…" : "Schedule appointment"}</Button></div></form></div> : null}
  </></AppointmentExamplesContext.Provider>;
}
function Field({ label, className, name, placeholder, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const examples = useContext(AppointmentExamplesContext); return <label className={className}><span className="mb-2 block text-xs font-bold text-slate-700">{label}</span><input name={name} placeholder={name === "title" ? examples.appointmentTitle : placeholder} required {...props} className="h-11 w-full rounded-lg border border-[var(--border)] px-3 text-sm outline-none" /></label>; }
function Select({ label, name, options, empty }: { label: string; name: string; options: Option[]; empty: string }) { return <label><span className="mb-2 block text-xs font-bold text-slate-700">{label}</span><select name={name} className="h-11 w-full rounded-lg border border-[var(--border)] bg-white px-3 text-sm"><option value="">{empty}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>; }
