import Link from "next/link";
import { CalendarDays, TrendingUp } from "lucide-react";
import { CategoryChart, PaymentChart } from "@/components/reports/report-charts";
import { ReportExportButton, type ReportExportRow } from "@/components/reports/report-export-button";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/ui/page-header";
import { moneyFor } from "@/lib/utils";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import { getBusinessPlatformConfig } from "@/lib/platform-config.server";
import { templateCatalogScope } from "@/lib/platform-config";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ period?: string }> }) {
  const session = await auth(); if (!session?.user) redirect("/login");
  const platform = await getBusinessPlatformConfig(session.user.businessId);
  if (!platform.modules.reports) redirect(session.user.role === "OWNER" ? "/settings" : "/");
  const selectedPeriod = (await searchParams).period;
  const period = selectedPeriod === "today" || selectedPeriod === "week" ? selectedPeriod : "month";
  const now = new Date(); const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const periodStart = period === "today" ? today : period === "week" ? new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6) : new Date(now.getFullYear(), now.getMonth(), 1); const businessId = session.user.businessId;
  const [transactions, items, products, settings] = await Promise.all([
    prisma.transaction.findMany({ where: { businessId, status: "COMPLETED", createdAt: { gte: periodStart } }, include: { payments: true }, orderBy: { createdAt: "desc" } }),
    prisma.transactionItem.findMany({ where: { transaction: { businessId, status: "COMPLETED", createdAt: { gte: periodStart } } }, include: { product: { include: { category: true } } } }),
    prisma.product.findMany({ where: { businessId, type: "PRODUCT", status: "ACTIVE", ...templateCatalogScope(platform.templateId) }, orderBy: { stock: "asc" } }),
    prisma.businessSettings.findUnique({ where: { businessId }, select: { currency: true } }),
  ]);
  const money = moneyFor(settings?.currency);
  const grossSales = transactions.reduce((sum, item) => sum + Number(item.total), 0); const units = items.reduce((sum, item) => sum + item.quantity, 0); const grossProfit = items.reduce((sum, item) => sum + Number(item.lineTotal) - Number(item.unitCost) * item.quantity, 0); const low = products.filter((item) => item.stock <= item.lowStockThreshold);
  const bestMap = new Map<string, { name: string; units: number; sales: number }>(); const categoryMap = new Map<string, number>();
  items.forEach((item) => { const current = bestMap.get(item.name) ?? { name: item.name, units: 0, sales: 0 }; current.units += item.quantity; current.sales += Number(item.lineTotal); bestMap.set(item.name, current); const category = item.product?.category?.name ?? "Uncategorized"; categoryMap.set(category, (categoryMap.get(category) ?? 0) + Number(item.lineTotal)); });
  const best = [...bestMap.values()].sort((a, b) => b.sales - a.sales).slice(0, 5); const categoryData = [...categoryMap].map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value).slice(0, 5);
  const paymentTotals = new Map<string, number>(); transactions.flatMap((item) => item.payments).forEach((payment) => paymentTotals.set(payment.method, (paymentTotals.get(payment.method) ?? 0) + Number(payment.amount))); const paymentColors: Record<string, string> = { CASH: "#176b4d", GCASH: "#4f86c6", CARD: "#d39b3a", OTHER: "#9aa5a0" }; const paymentData = [...paymentTotals].map(([name, value]) => ({ name: name === "GCASH" ? "GCash" : name.toLowerCase().replace(/^./, (letter) => letter.toUpperCase()), value: grossSales ? value / grossSales * 100 : 0, color: paymentColors[name] }));
  const periodLabel = period === "today" ? "Today" : period === "week" ? "Last 7 days" : "This month";
  const exportRows: ReportExportRow[] = transactions.map((transaction) => ({ receipt: transaction.receiptNumber, date: transaction.createdAt.toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Manila" }), payment: transaction.payments[0]?.method === "GCASH" ? "GCash" : transaction.payments[0]?.method.toLowerCase().replace(/^./, (letter) => letter.toUpperCase()) ?? "Other", total: Number(transaction.total) }));
  return <div className="mx-auto max-w-[1500px]"><PageHeader eyebrow="Business insights" title="Reports" description={`Understand sales and ${platform.terminology.transaction.toLowerCase()} performance with focused reporting.`} actions={<><span className="flex h-10 items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-xs font-semibold text-[var(--ink-soft)]"><CalendarDays size={15} /> {periodStart.toLocaleDateString("en-PH", { month: "short", day: "numeric" })}–{now.toLocaleDateString("en-PH", { day: "numeric", year: "numeric" })}</span><ReportExportButton rows={exportRows} period={period} /></>} />
    <div className="mt-6 flex w-fit rounded-lg border border-[var(--border)] bg-[var(--surface)] p-1">{(["today", "week", "month"] as const).map((item) => <Link key={item} href={`/reports?period=${item}`} className={`rounded-md px-4 py-2 text-xs font-bold ${period === item ? "bg-[var(--brand)] text-white" : "text-[var(--muted)] hover:bg-[var(--surface-subtle)]"}`}>{item === "today" ? "Daily" : item === "week" ? "Weekly" : "Monthly"}</Link>)}</div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><ReportMetric label="Gross sales" value={money.format(grossSales)} note={`Completed sales · ${periodLabel}`} /><ReportMetric label="Transactions" value={String(transactions.length)} note={`${money.format(transactions.length ? grossSales / transactions.length : 0)} average value`} /><ReportMetric label="Items sold" value={String(units)} note={`${transactions.length ? (units / transactions.length).toFixed(2) : "0"} items per sale`} /><ReportMetric label="Gross profit" value={money.format(grossProfit)} note={`${grossSales ? (grossProfit / grossSales * 100).toFixed(1) : "0"}% estimated margin`} /></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><article className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex justify-between"><div><h2 className="font-display font-semibold text-[var(--foreground)]">Sales by category</h2><p className="mt-1 text-xs text-[var(--muted)]">Revenue contribution · {periodLabel}</p></div><TrendingUp size={18} className="text-emerald-600" /></div><CategoryChart data={categoryData} currency={settings?.currency} /></article><article className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-display font-semibold text-[var(--foreground)]">Sales by payment method</h2><p className="mt-1 text-xs text-[var(--muted)]">Share of completed transaction value · {periodLabel}</p><PaymentChart data={paymentData} /></article></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-[1.35fr_0.65fr]"><article className="overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] px-5 py-4"><h2 className="font-display font-semibold text-[var(--foreground)]">Best-selling items</h2><p className="mt-1 text-xs text-[var(--muted)]">Ranked by revenue · {periodLabel}</p></div><table className="w-full text-left"><thead><tr className="bg-[var(--surface-subtle)] text-[10px] uppercase tracking-wider text-[var(--muted)]"><th className="px-5 py-3">Rank</th><th className="px-4 py-3">Item</th><th className="px-4 py-3 text-right">Units</th><th className="px-5 py-3 text-right">Sales</th></tr></thead><tbody className="divide-y divide-dashed divide-[var(--border)]">{best.map((item, index) => <tr key={item.name}><td className="px-5 py-3.5"><span className="grid size-6 place-items-center rounded-full bg-[var(--surface-subtle)] text-[10px] font-bold text-[var(--muted)]">{index + 1}</span></td><td className="px-4 py-3.5 text-xs font-bold text-[var(--foreground)]">{item.name}</td><td className="px-4 py-3.5 text-right text-xs text-[var(--ink-soft)]">{item.units}</td><td className="px-5 py-3.5 text-right text-xs font-bold">{money.format(item.sales)}</td></tr>)}</tbody></table>{!best.length ? <p className="px-5 py-10 text-center text-xs text-[var(--muted)]">No completed sales in this period.</p> : null}</article><article className="rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="border-b border-[var(--border)] px-5 py-4"><h2 className="font-display font-semibold text-[var(--foreground)]">Low-stock report</h2><p className="mt-1 text-xs text-[var(--muted)]">Requires attention</p></div><div className="divide-y divide-dashed divide-[var(--border)] px-5">{low.map((item) => <div key={item.id} className="flex items-center justify-between py-4"><div><p className="text-xs font-bold text-[var(--foreground)]">{item.name}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{item.sku}</p></div><Badge tone="warning">{item.stock} left</Badge></div>)}{!low.length ? <p className="py-10 text-center text-xs text-[var(--muted)]">All products are above their thresholds.</p> : null}</div></article></div>
  </div>;
}

function ReportMetric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><p className="text-xs font-semibold text-[var(--muted)]">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-[var(--foreground)]">{value}</p><p className="mt-2 text-[11px] font-medium text-emerald-700">{note}</p></article>; }
