"use client";

import { createContext, useContext, useState } from "react";
import { useRouter } from "next/navigation";
import { ClipboardPlus, Wrench, X } from "lucide-react";
import { createJobOrder, updateJobOrderStatus } from "@/app/actions/modules";
import { Button } from "@/components/ui/button";
import { moneyFor } from "@/lib/utils";
import { defaultTemplateExamples, type TemplateExamples } from "@/lib/platform-config";

type Option = { id: string; name: string };
export type JobOrderRow = { id: string; referenceNumber: string; title: string; customer: string; item: string; assignedTo: string; status: "OPEN" | "IN_PROGRESS" | "WAITING_PARTS" | "READY" | "COMPLETED" | "CANCELLED"; estimatedAmount: number | null; due: string; description: string };
const JobOrderExamplesContext = createContext(defaultTemplateExamples);

export function JobOrderManager({ jobOrders, customers, products, staff, currency, examples = defaultTemplateExamples }: { jobOrders: JobOrderRow[]; customers: Option[]; products: Option[]; staff: Option[]; currency: string; examples?: TemplateExamples }) {
  const money = moneyFor(currency); const router = useRouter(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function create(formData: FormData) { setSaving(true); const amount = String(formData.get("estimatedAmount")); const result = await createJobOrder({ title: String(formData.get("title")), customerId: String(formData.get("customerId")), productId: String(formData.get("productId")), assignedToId: String(formData.get("assignedToId")), description: String(formData.get("description")), estimatedAmount: amount ? Number(amount) : undefined, dueAt: String(formData.get("dueAt")), notes: String(formData.get("notes")) }); setSaving(false); if (!result.ok) { setError(result.error); return; } setOpen(false); setError(""); router.refresh(); }
  async function changeStatus(id: string, status: JobOrderRow["status"]) { const result = await updateJobOrderStatus({ id, status }); if (!result.ok) setError(result.error); else router.refresh(); }
  return <JobOrderExamplesContext.Provider value={examples}><>
    <div className="flex justify-end"><Button onClick={() => setOpen(true)}><ClipboardPlus size={16} /> New job order</Button></div>
    {error ? <p className="mt-4 rounded-lg bg-red-50 px-4 py-3 text-xs font-semibold text-red-700">{error}</p> : null}
    <div className="mt-4 overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--surface)]"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left"><thead><tr className="border-b border-[var(--border)] bg-[var(--surface-subtle)] text-[10px] uppercase tracking-wider text-[var(--muted)]"><th className="px-5 py-3">Reference</th><th className="px-4 py-3">Job</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Assigned to</th><th className="px-4 py-3 text-right">Estimate</th><th className="px-4 py-3">Due</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-dashed divide-[var(--border)]">{jobOrders.map((item) => <tr key={item.id} className="hover:bg-[var(--surface-subtle)]"><td className="px-5 py-4 text-xs font-bold text-[var(--brand)]">{item.referenceNumber}</td><td className="px-4 py-4"><p className="text-xs font-bold text-[var(--foreground)]">{item.title}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{item.item}</p>{item.description ? <p className="mt-1 max-w-xs truncate text-[10px] text-[var(--muted)]">{item.description}</p> : null}</td><td className="px-4 py-4 text-xs text-[var(--ink-soft)]">{item.customer}</td><td className="px-4 py-4 text-xs text-[var(--ink-soft)]">{item.assignedTo}</td><td className="px-4 py-4 text-right text-xs font-bold">{item.estimatedAmount === null ? "—" : money.format(item.estimatedAmount)}</td><td className="px-4 py-4 text-xs text-[var(--muted)]">{item.due}</td><td className="px-5 py-4"><select value={item.status} onChange={(event) => changeStatus(item.id, event.target.value as JobOrderRow["status"])} className="h-9 rounded-lg border border-[var(--border)] bg-[var(--surface)] px-2 text-xs font-semibold"><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="WAITING_PARTS">Waiting for parts</option><option value="READY">Ready</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></td></tr>)}</tbody></table></div>{!jobOrders.length ? <div className="px-6 py-14 text-center"><Wrench className="mx-auto text-[var(--border)]" size={28} /><p className="mt-3 text-sm font-bold text-[var(--ink-soft)]">No job orders yet</p><p className="mt-1 text-xs text-[var(--muted)]">Create the first repair or service job.</p></div> : null}<div className="border-t border-[var(--border)] px-5 py-3 text-[11px] text-[var(--muted)]">{jobOrders.length} job order{jobOrders.length === 1 ? "" : "s"}</div></div>
    {open ? <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/50 p-4"><form action={create} className="my-8 w-full max-w-2xl rounded-2xl bg-[var(--surface)] shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--border)] px-6 py-5"><div><h2 className="font-display text-lg font-semibold">New job order</h2><p className="mt-1 text-xs text-[var(--muted)]">Track a repair, installation, or service request.</p></div><button type="button" onClick={() => setOpen(false)}><X size={19} className="text-[var(--muted)]" /></button></div><div className="grid gap-4 p-6 sm:grid-cols-2"><Field name="title" label="Job title" placeholder="Brake inspection and repair" className="sm:col-span-2" /><Select name="customerId" label="Customer" options={customers} empty="No linked customer" /><Select name="productId" label="Product or service" options={products} empty="No linked item" /><Select name="assignedToId" label="Assigned staff" options={staff} empty="Unassigned" /><Field name="dueAt" type="date" label="Due date" required={false} /><Field name="estimatedAmount" type="number" min="0" step="0.01" label="Estimated amount" required={false} /><span /><label className="sm:col-span-2"><span className="mb-2 block text-xs font-bold text-[var(--ink-soft)]">Description</span><textarea name="description" rows={3} className="w-full rounded-lg border border-[var(--border)] p-3 text-sm outline-none" /></label><label className="sm:col-span-2"><span className="mb-2 block text-xs font-bold text-[var(--ink-soft)]">Internal notes</span><textarea name="notes" rows={2} className="w-full rounded-lg border border-[var(--border)] p-3 text-sm outline-none" /></label>{error ? <p className="sm:col-span-2 text-xs font-semibold text-red-700">{error}</p> : null}</div><div className="flex justify-end gap-2 border-t border-[var(--border)] p-4"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Creating…" : "Create job order"}</Button></div></form></div> : null}
  </></JobOrderExamplesContext.Provider>;
}
function Field({ label, className, required = true, name, placeholder, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const examples = useContext(JobOrderExamplesContext); return <label className={className}><span className="mb-2 block text-xs font-bold text-[var(--ink-soft)]">{label}</span><input name={name} placeholder={name === "title" ? examples.jobOrderTitle : placeholder} required={required} {...props} className="h-11 w-full rounded-lg border border-[var(--border)] px-3 text-sm outline-none" /></label>; }
function Select({ label, name, options, empty }: { label: string; name: string; options: Option[]; empty: string }) { return <label><span className="mb-2 block text-xs font-bold text-[var(--ink-soft)]">{label}</span><select name={name} className="h-11 w-full rounded-lg border border-[var(--border)] bg-[var(--surface)] px-3 text-sm"><option value="">{empty}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>; }
